create table seller (
    id int primary key generated by default as identity ,
    name varchar(50) not null ,
    contact_info varchar(100) not null unique,
    registration_date timestamp not null default current_timestamp
);

create table transaction (
    id int primary key generated by default as identity ,
    seller int not null references seller("id") on delete set null ,
    amount int not null check ( amount > 0 ) ,
    paymentType varchar(8) not null ,
    transaction_date timestamp not null default current_timestamp
);
